#if !canImport(ObjectiveC)
import XCTest

extension CommonMarkSpecTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommonMarkSpecTests = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommonMarkSpecTests.__allTests__CommonMarkSpecTests),
    ]
}
#endif
