excluded:
  - .build
  - .git
  - .**/XCTestManifests.swift
  - ./Tests/MarkdownKitTests/CommonMarkSpec.swift
disabled_rules:
  - cyclomatic_complexity
  - identifier_name
  - leading_whitespace
  - line_length
  - nesting
  - trailing_comma
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_direct_init
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order
  - multiline_function_chains
  - multiline_parameters
  - no_extension_access_modifier
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - xct_specific_matcher
  - yoda_condition
