name: tests

on: [push]

jobs:

  linux-5_1:
    name: Linux (Swift 5.1)
    runs-on: ubuntu-latest
    container:
      image: swift:5.1
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v -c release

  macos:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v -c release
