name: tests

on:
  - push
  - pull_request

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - "swift:5.1"
          - "swift:5.2"
          - "swift:5.3"
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Release Build
      run: swift build --enable-test-discovery -v -c release
    - name: Debug Build
      run: swift build --enable-test-discovery -v -c debug
    - name: Debug Test
      run: swift test --enable-test-discovery -v -c debug

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Release Build
      run: swift build -v -c release
    - name: Release Test
      run: swift test -v -c release
    - name: Debug Build
      run: swift build -v -c debug
    - name: Debug Test
      run: swift test -v -c debug
